// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.option(__t.string()),
  online: __t.bool(),
  x: __t.f32(),
  z: __t.f32(),
  facingX: __t.f32(),
  facingZ: __t.f32(),
  updatedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

